{"hierarchy":{"paths":[["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/RejectionReason"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"notRelated"}],"roleHeading":"Case","modules":[{"name":"AnswerBotProvidersSDK"}],"navigatorTitle":[{"text":"ZDKRejectionReasonNotRelated","kind":"identifier"}],"symbolKind":"case","title":"RejectionReason.notRelated","role":"symbol","externalID":"c:@M@AnswerBotProvidersSDK@E@ZDKRejectionReason@ZDKRejectionReasonNotRelated"},"identifier":{"url":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/RejectionReason\/notRelated","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notRelated","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/answerbotproviderssdk\/rejectionreason\/notrelated"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/answerbotproviderssdk\/rejectionreason\/notrelated"]}],"kind":"symbol","sections":[],"references":{"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK":{"title":"AnswerBotProvidersSDK","kind":"symbol","url":"\/documentation\/answerbotproviderssdk","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK","type":"topic"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/RejectionReason/notRelated":{"abstract":[],"url":"\/documentation\/answerbotproviderssdk\/rejectionreason\/notrelated","navigatorTitle":[{"kind":"identifier","text":"ZDKRejectionReasonNotRelated"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/RejectionReason\/notRelated","title":"RejectionReason.notRelated","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"notRelated"}]},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/RejectionReason":{"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/RejectionReason","kind":"symbol","type":"topic","navigatorTitle":[{"text":"RejectionReason","kind":"identifier"}],"abstract":[],"role":"symbol","url":"\/documentation\/answerbotproviderssdk\/rejectionreason","title":"RejectionReason","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"RejectionReason","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"ZDKRejectionReasonNotRelated","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"ZDKRejectionReasonNotRelated","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"ZDKRejectionReasonNotRelated","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1RejectionReason~1notRelated\/title","value":"ZDKRejectionReasonNotRelated"},{"op":"replace","value":[{"text":"ZDKRejectionReasonNotRelated","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1RejectionReason~1notRelated\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1RejectionReason\/title","op":"replace","value":"ZDKRejectionReason"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1RejectionReason\/fragments","value":[{"kind":"identifier","text":"ZDKRejectionReason"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}