{"identifier":{"url":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettings","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/answerbotproviderssdk\/answerbotsettings"]},{"paths":["\/documentation\/answerbotproviderssdk\/answerbotsettings"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettings\/init()","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettings\/init(from:)"]},{"identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettings\/enabled"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettings\/DefaultType"],"title":"Type Aliases"},{"title":"Type Properties","identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettings\/default"]}],"metadata":{"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AnswerBotSettings"}],"roleHeading":"Class","modules":[{"name":"AnswerBotProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"AnswerBotSettings"}],"externalID":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKAnswerBotSettings","role":"symbol","title":"AnswerBotSettings"},"abstract":[{"type":"text","text":"The AnswerBot Settings model"}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/Se","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/SQ","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/SH","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/14ZendeskCoreSDK16DecodableDefaultP"],"title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(ZDKAnswerBotSettings) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AnswerBotSettings"}],"languages":["swift"]}]}],"references":{"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotSettings/enabled":{"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettings\/enabled","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"enabled","kind":"identifier"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"Bool"},{"type":"text","text":" indicates whether Answer Bot is enabled"}],"url":"\/documentation\/answerbotproviderssdk\/answerbotsettings\/enabled","kind":"symbol","type":"topic","role":"symbol","title":"enabled"},"doc://com.zendesk.AnswerBotProvidersSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotSettings/DefaultType":{"url":"\/documentation\/answerbotproviderssdk\/answerbotsettings\/defaulttype","title":"AnswerBotSettings.DefaultType","kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"DefaultType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DefaultType"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettings\/DefaultType"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK":{"type":"topic","kind":"symbol","url":"\/documentation\/answerbotproviderssdk","title":"AnswerBotProvidersSDK","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK","abstract":[],"role":"collection"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotSettings/init()":{"abstract":[],"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettings\/init()","title":"init()","type":"topic","url":"\/documentation\/answerbotproviderssdk\/answerbotsettings\/init()","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"kind":"symbol"},"doc://com.zendesk.AnswerBotProvidersSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/SQ"},"doc://com.zendesk.AnswerBotProvidersSDK/14ZendeskCoreSDK16DecodableDefaultP":{"title":"ZendeskCoreSDK.DecodableDefault","type":"unresolvable","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/14ZendeskCoreSDK16DecodableDefaultP"},"doc://com.zendesk.AnswerBotProvidersSDK/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/Se"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotSettings/default":{"abstract":[],"role":"symbol","title":"default","url":"\/documentation\/answerbotproviderssdk\/answerbotsettings\/default","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettings\/default","type":"topic","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"`default`","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnswerBotSettings","preciseIdentifier":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKAnswerBotSettings"}]},"doc://com.zendesk.AnswerBotProvidersSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/objc(cs)NSObject"},"doc://com.zendesk.AnswerBotProvidersSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/SH"},"doc://com.zendesk.AnswerBotProvidersSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/s7CVarArgP"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotSettings/init(from:)":{"type":"topic","url":"\/documentation\/answerbotproviderssdk\/answerbotsettings\/init(from:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettings\/init(from:)","role":"symbol","title":"init(from:)","kind":"symbol"},"doc://com.zendesk.AnswerBotProvidersSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotSettings":{"role":"symbol","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettings","url":"\/documentation\/answerbotproviderssdk\/answerbotsettings","abstract":[{"text":"The AnswerBot Settings model","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AnswerBotSettings","kind":"identifier"}],"type":"topic","title":"AnswerBotSettings","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AnswerBotSettings"}]},"doc://com.zendesk.AnswerBotProvidersSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/objc(pl)NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","value":"ZDKAnswerBotSettings","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKAnswerBotSettings"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ZDKAnswerBotSettings"}]},{"value":[{"identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettings\/enabled"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettings\/init()"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/objc(cs)NSObject"],"title":"Inherits From"}],"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKAnswerBotSettings","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"enabled","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotSettings~1enabled\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotSettings~1enabled\/fragments","op":"replace","value":[{"kind":"identifier","text":"enabled"}]},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotSettings~1init()\/title","op":"replace","value":"init"},{"value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotSettings~1init()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotSettings\/title","op":"replace","value":"ZDKAnswerBotSettings"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKAnswerBotSettings"}],"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotSettings\/fragments"}]}]}