{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/answerbotproviderssdk\/deflection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/answerbotproviderssdk\/deflection"]}],"metadata":{"externalID":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKDeflection","role":"symbol","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Deflection","kind":"identifier"}],"modules":[{"name":"AnswerBotProvidersSDK"}],"title":"Deflection","navigatorTitle":[{"text":"Deflection","kind":"identifier"}],"roleHeading":"Class"},"kind":"symbol","relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/Se","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/SE","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/SQ","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/SH"],"title":"Conforms To"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/Deflection\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/Deflection\/deflectionID"]},{"identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/Deflection\/isEqual(_:)"],"title":"Instance Methods"}],"identifier":{"url":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/Deflection","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(ZDKDeflection) "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Deflection","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK":{"type":"topic","kind":"symbol","url":"\/documentation\/answerbotproviderssdk","title":"AnswerBotProvidersSDK","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK","abstract":[],"role":"collection"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/Deflection/deflectionID":{"role":"symbol","url":"\/documentation\/answerbotproviderssdk\/deflection\/deflectionid","abstract":[],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"deflectionID","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"}],"title":"deflectionID","type":"topic","navigatorTitle":[{"text":"deflectionID","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/Deflection\/deflectionID","kind":"symbol"},"doc://com.zendesk.AnswerBotProvidersSDK/SE":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/SE","title":"Swift.Encodable"},"doc://com.zendesk.AnswerBotProvidersSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/Deflection/init(from:)":{"role":"symbol","url":"\/documentation\/answerbotproviderssdk\/deflection\/init(from:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"title":"init(from:)","type":"topic","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/Deflection\/init(from:)","kind":"symbol"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/Deflection":{"url":"\/documentation\/answerbotproviderssdk\/deflection","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/Deflection","type":"topic","kind":"symbol","title":"Deflection","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Deflection"}],"navigatorTitle":[{"kind":"identifier","text":"Deflection"}],"role":"symbol","abstract":[]},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/Deflection/isEqual(_:)":{"role":"symbol","url":"\/documentation\/answerbotproviderssdk\/deflection\/isequal(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isEqual(_:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/Deflection\/isEqual(_:)","kind":"symbol"},"doc://com.zendesk.AnswerBotProvidersSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/SH"},"doc://com.zendesk.AnswerBotProvidersSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/SQ"},"doc://com.zendesk.AnswerBotProvidersSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/s7CVarArgP"},"doc://com.zendesk.AnswerBotProvidersSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/objc(cs)NSObject"},"doc://com.zendesk.AnswerBotProvidersSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.AnswerBotProvidersSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.AnswerBotProvidersSDK/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/Se"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ZDKDeflection","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"kind":"identifier","text":"ZDKDeflection"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKDeflection","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/Deflection\/deflectionID"]},{"identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/Deflection\/isEqual(_:)"],"title":"Instance Methods"}]},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKDeflection","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}]}},{"value":"deflectionID","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1Deflection~1deflectionID\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1Deflection~1deflectionID\/fragments","value":[{"text":"deflectionID","kind":"identifier"}]},{"value":"ZDKDeflection","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1Deflection\/title","op":"replace"},{"value":[{"text":"ZDKDeflection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1Deflection\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1Deflection~1isEqual(_:)\/title","value":"isEqual:","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1Deflection~1isEqual(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]}]}]}