{"hierarchy":{"paths":[["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotDispatcherResponse"]]},"metadata":{"roleHeading":"Instance Property","title":"response","modules":[{"name":"AnswerBotProvidersSDK"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"response","kind":"identifier"},{"kind":"text","text":": "},{"text":"HTTPURLResponse","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSHTTPURLResponse"}],"role":"symbol","symbolKind":"property","externalID":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKAnswerBotDispatcherResponse(py)response","navigatorTitle":[{"text":"response","kind":"identifier"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"response","kind":"identifier"},{"kind":"text","text":": "},{"text":"HTTPURLResponse","preciseIdentifier":"c:objc(cs)NSHTTPURLResponse","kind":"typeIdentifier"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/answerbotproviderssdk\/answerbotdispatcherresponse\/response"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/answerbotproviderssdk\/answerbotdispatcherresponse\/response"]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotDispatcherResponse\/response"},"references":{"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotDispatcherResponse/response":{"url":"\/documentation\/answerbotproviderssdk\/answerbotdispatcherresponse\/response","abstract":[],"kind":"symbol","title":"response","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotDispatcherResponse\/response","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"response"},{"kind":"text","text":": "},{"text":"HTTPURLResponse","preciseIdentifier":"c:objc(cs)NSHTTPURLResponse","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"response","kind":"identifier"}]},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK":{"url":"\/documentation\/answerbotproviderssdk","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK","kind":"symbol","type":"topic","abstract":[],"title":"AnswerBotProvidersSDK","role":"collection"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotDispatcherResponse":{"abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AnswerBotDispatcherResponse","kind":"identifier"}],"navigatorTitle":[{"text":"AnswerBotDispatcherResponse","kind":"identifier"}],"url":"\/documentation\/answerbotproviderssdk\/answerbotdispatcherresponse","title":"AnswerBotDispatcherResponse","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotDispatcherResponse"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"response","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"response","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSHTTPURLResponse","kind":"typeIdentifier","text":"NSHTTPURLResponse"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"response"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"response","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotDispatcherResponse~1response\/title"},{"op":"replace","value":[{"kind":"identifier","text":"response"}],"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotDispatcherResponse~1response\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotDispatcherResponse\/title","value":"ZDKAnswerBotDispatcherResponse"},{"op":"replace","value":[{"text":"ZDKAnswerBotDispatcherResponse","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotDispatcherResponse\/fragments"}]}]}