{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"url"}],"role":"symbol","symbolKind":"property","externalID":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKDeflectionArticle(py)url","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"modules":[{"name":"AnswerBotProvidersSDK"}],"title":"url"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionArticle"]]},"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionArticle\/url","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/answerbotproviderssdk\/deflectionarticle\/url"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/answerbotproviderssdk\/deflectionarticle\/url"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]}]}],"kind":"symbol","references":{"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/DeflectionArticle":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DeflectionArticle","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionArticle","title":"DeflectionArticle","navigatorTitle":[{"text":"DeflectionArticle","kind":"identifier"}],"url":"\/documentation\/answerbotproviderssdk\/deflectionarticle","kind":"symbol","abstract":[]},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/DeflectionArticle/url":{"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionArticle\/url","title":"url","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"url","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/answerbotproviderssdk\/deflectionarticle\/url","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"url"}],"kind":"symbol","type":"topic"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK":{"url":"\/documentation\/answerbotproviderssdk","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK","kind":"symbol","type":"topic","abstract":[],"title":"AnswerBotProvidersSDK","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"url","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"url"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"url"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1DeflectionArticle\/title","op":"replace","value":"ZDKDeflectionArticle"},{"value":[{"text":"ZDKDeflectionArticle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1DeflectionArticle\/fragments"},{"value":"url","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1DeflectionArticle~1url\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1DeflectionArticle~1url\/fragments","value":[{"text":"url","kind":"identifier"}],"op":"replace"}]}]}