{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/answerbotproviderssdk\/rejectionreason\/relatedbutdidntanswer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/answerbotproviderssdk\/rejectionreason\/relatedbutdidntanswer"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/RejectionReason"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/RejectionReason\/relatedButDidntAnswer"},"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"relatedButDidntAnswer"}],"symbolKind":"case","navigatorTitle":[{"text":"ZDKRejectionReasonRelatedButDidntAnswer","kind":"identifier"}],"modules":[{"name":"AnswerBotProvidersSDK"}],"externalID":"c:@M@AnswerBotProvidersSDK@E@ZDKRejectionReason@ZDKRejectionReasonRelatedButDidntAnswer","title":"RejectionReason.relatedButDidntAnswer"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"relatedButDidntAnswer"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/RejectionReason":{"abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RejectionReason"}],"navigatorTitle":[{"kind":"identifier","text":"RejectionReason"}],"url":"\/documentation\/answerbotproviderssdk\/rejectionreason","title":"RejectionReason","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/RejectionReason"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK":{"url":"\/documentation\/answerbotproviderssdk","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK","kind":"symbol","type":"topic","abstract":[],"title":"AnswerBotProvidersSDK","role":"collection"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/RejectionReason/relatedButDidntAnswer":{"role":"symbol","url":"\/documentation\/answerbotproviderssdk\/rejectionreason\/relatedbutdidntanswer","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"relatedButDidntAnswer"}],"title":"RejectionReason.relatedButDidntAnswer","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/RejectionReason\/relatedButDidntAnswer","navigatorTitle":[{"text":"ZDKRejectionReasonRelatedButDidntAnswer","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"ZDKRejectionReasonRelatedButDidntAnswer"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"ZDKRejectionReasonRelatedButDidntAnswer","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"ZDKRejectionReasonRelatedButDidntAnswer","kind":"identifier"}],"languages":["occ"]}]}},{"value":"ZDKRejectionReason","op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1RejectionReason\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1RejectionReason\/fragments","value":[{"text":"ZDKRejectionReason","kind":"identifier"}]},{"value":"ZDKRejectionReasonRelatedButDidntAnswer","op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1RejectionReason~1relatedButDidntAnswer\/title"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1RejectionReason~1relatedButDidntAnswer\/fragments","value":[{"kind":"identifier","text":"ZDKRejectionReasonRelatedButDidntAnswer"}],"op":"replace"}]}]}