{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","symbolKind":"class","navigatorTitle":[{"text":"AnswerBotSettingsProvider","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AnswerBotSettingsProvider"}],"modules":[{"name":"AnswerBotProvidersSDK"}],"roleHeading":"Class","title":"AnswerBotSettingsProvider","externalID":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKAnswerBotSettingsProvider"},"topicSections":[{"identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettingsProvider\/getSettings(callback:)"],"title":"Type Methods"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettingsProviderProtocol","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/SQ","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/SH"],"kind":"relationships"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettingsProvider"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKAnswerBotSettingsProvider) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AnswerBotSettingsProvider","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"level":2,"anchor":"overview","type":"heading","text":"Overview"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ZDKAnswerBotSettingsProvider"},{"text":" is used to fetch the latest settings from the network\/local cache.","type":"text"}]}]}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/answerbotproviderssdk\/answerbotsettingsprovider"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/answerbotproviderssdk\/answerbotsettingsprovider"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.zendesk.AnswerBotProvidersSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/objc(cs)NSObject"},"doc://com.zendesk.AnswerBotProvidersSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/SQ"},"doc://com.zendesk.AnswerBotProvidersSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/SH"},"doc://com.zendesk.AnswerBotProvidersSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotSettingsProvider/getSettings(callback:)":{"navigatorTitle":[{"text":"getSettingsWithCallback:","kind":"identifier"}],"abstract":[{"text":"Fetches an ","type":"text"},{"code":"AnswerBotSettings","type":"codeVoice"},{"text":" from the network\/local cache.","type":"text"}],"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettingsProvider\/getSettings(callback:)","url":"\/documentation\/answerbotproviderssdk\/answerbotsettingsprovider\/getsettings(callback:)","title":"getSettings(callback:)","kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getSettings"},{"text":"(","kind":"text"},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKAnswerBotSettings","text":"AnswerBotSettings"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}]},"doc://com.zendesk.AnswerBotProvidersSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/objc(pl)NSObject"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotSettingsProviderProtocol":{"abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AnswerBotSettingsProviderProtocol"}],"navigatorTitle":[{"kind":"identifier","text":"AnswerBotSettingsProviderProtocol"}],"url":"\/documentation\/answerbotproviderssdk\/answerbotsettingsproviderprotocol","title":"AnswerBotSettingsProviderProtocol","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettingsProviderProtocol"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK":{"url":"\/documentation\/answerbotproviderssdk","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK","kind":"symbol","type":"topic","abstract":[],"title":"AnswerBotProvidersSDK","role":"collection"},"doc://com.zendesk.AnswerBotProvidersSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotSettingsProvider":{"abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AnswerBotSettingsProvider"}],"navigatorTitle":[{"kind":"identifier","text":"AnswerBotSettingsProvider"}],"url":"\/documentation\/answerbotproviderssdk\/answerbotsettingsprovider","title":"AnswerBotSettingsProvider","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettingsProvider"},"doc://com.zendesk.AnswerBotProvidersSDK/s7CVarArgP":{"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ZDKAnswerBotSettingsProvider"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"text":"ZDKAnswerBotSettingsProvider","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"ZDKAnswerBotSettingsProvider","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"title":"Type Methods","identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettingsProvider\/getSettings(callback:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKAnswerBotSettingsProvider","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotSettingsProvider~1getSettings(callback:)\/title","op":"replace","value":"getSettingsWithCallback:"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getSettingsWithCallback:"}],"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotSettingsProvider~1getSettings(callback:)\/fragments"},{"value":"ZDKAnswerBotSettingsProvider","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotSettingsProvider\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKAnswerBotSettingsProvider"}],"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotSettingsProvider\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}