{"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionResponse\/init(from:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionResponse\/deflection","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionResponse\/deflectionArticles","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionResponse\/interactionAccessToken"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionResponse\/isEqual(_:)"]}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/objc(cs)NSObject"]},{"title":"Conforms To","identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/Se","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/SE","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/SQ","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/SH"],"type":"conformsTo","kind":"relationships"}],"metadata":{"externalID":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKDeflectionResponse","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DeflectionResponse"}],"navigatorTitle":[{"text":"DeflectionResponse","kind":"identifier"}],"symbolKind":"class","role":"symbol","modules":[{"name":"AnswerBotProvidersSDK"}],"roleHeading":"Class","title":"DeflectionResponse"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK"]]},"identifier":{"url":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionResponse","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(ZDKDeflectionResponse) ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DeflectionResponse","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/answerbotproviderssdk\/deflectionresponse"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/answerbotproviderssdk\/deflectionresponse"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/DeflectionResponse/deflection":{"navigatorTitle":[{"text":"deflection","kind":"identifier"}],"role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/answerbotproviderssdk\/deflectionresponse\/deflection","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionResponse\/deflection","kind":"symbol","title":"deflection","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"deflection","kind":"identifier"},{"kind":"text","text":": "},{"text":"Deflection","preciseIdentifier":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKDeflection","kind":"typeIdentifier"}]},"doc://com.zendesk.AnswerBotProvidersSDK/Se":{"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK":{"url":"\/documentation\/answerbotproviderssdk","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK","kind":"symbol","type":"topic","abstract":[],"title":"AnswerBotProvidersSDK","role":"collection"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/DeflectionResponse/deflectionArticles":{"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"deflectionArticles","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKDeflectionArticle","text":"DeflectionArticle"},{"text":"]","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionResponse\/deflectionArticles","title":"deflectionArticles","navigatorTitle":[{"text":"deflectionArticles","kind":"identifier"}],"url":"\/documentation\/answerbotproviderssdk\/deflectionresponse\/deflectionarticles","kind":"symbol","abstract":[]},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/DeflectionResponse/isEqual(_:)":{"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/answerbotproviderssdk\/deflectionresponse\/isequal(_:)","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionResponse\/isEqual(_:)","kind":"symbol","title":"isEqual(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.zendesk.AnswerBotProvidersSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/s7CVarArgP"},"doc://com.zendesk.AnswerBotProvidersSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/SQ"},"doc://com.zendesk.AnswerBotProvidersSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/SH"},"doc://com.zendesk.AnswerBotProvidersSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/DeflectionResponse":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DeflectionResponse"}],"type":"topic","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionResponse","title":"DeflectionResponse","navigatorTitle":[{"kind":"identifier","text":"DeflectionResponse"}],"kind":"symbol","url":"\/documentation\/answerbotproviderssdk\/deflectionresponse","abstract":[]},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/DeflectionResponse/init(from:)":{"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionResponse\/init(from:)","title":"init(from:)","url":"\/documentation\/answerbotproviderssdk\/deflectionresponse\/init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"kind":"symbol","abstract":[],"role":"symbol","type":"topic"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/DeflectionResponse/interactionAccessToken":{"navigatorTitle":[{"text":"interactionAccessToken","kind":"identifier"}],"role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/answerbotproviderssdk\/deflectionresponse\/interactionaccesstoken","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionResponse\/interactionAccessToken","kind":"symbol","title":"interactionAccessToken","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"interactionAccessToken","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"doc://com.zendesk.AnswerBotProvidersSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.zendesk.AnswerBotProvidersSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.zendesk.AnswerBotProvidersSDK/SE":{"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://com.zendesk.AnswerBotProvidersSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/objc(pl)NSObject","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ZDKDeflectionResponse","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ZDKDeflectionResponse","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"ZDKDeflectionResponse"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionResponse\/deflection","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionResponse\/deflectionArticles","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionResponse\/interactionAccessToken"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionResponse\/isEqual(_:)"]}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/objc(cs)NSObject"]}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"ZDKDeflectionResponse","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1DeflectionResponse~1deflection\/title","value":"deflection","op":"replace"},{"value":[{"text":"deflection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1DeflectionResponse~1deflection\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1DeflectionResponse~1deflectionArticles\/title","value":"deflectionArticles"},{"op":"replace","value":[{"text":"deflectionArticles","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1DeflectionResponse~1deflectionArticles\/fragments"},{"op":"replace","value":"isEqual:","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1DeflectionResponse~1isEqual(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1DeflectionResponse~1isEqual(_:)\/fragments"},{"value":"ZDKDeflectionResponse","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1DeflectionResponse\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKDeflectionResponse"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1DeflectionResponse\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1DeflectionResponse~1interactionAccessToken\/title","value":"interactionAccessToken"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1DeflectionResponse~1interactionAccessToken\/fragments","op":"replace","value":[{"kind":"identifier","text":"interactionAccessToken"}]}]}]}