{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDeflectionForQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"query"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" (("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionResponse","preciseIdentifier":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKDeflectionResponse","text":"DeflectionResponse"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"query","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The String query sent to Answer Bot"}]}]},{"name":"callback","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Callback that will deliver the DeflectionResponse"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/answerbotproviderssdk\/answerbotprovider\/getdeflectionforquery(query:callback:)-5i9ze"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/answerbotproviderssdk\/answerbotprovider\/getdeflectionforquery(query:callback:)-5i9ze"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvider\/getDeflectionForQuery(query:callback:)-5i9ze","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Gets a DeflectionResponse for the given query String. The DeflectionResponse"},{"type":"text","text":" "},{"type":"text","text":"contains an array of DeflectionArticles that match the query. The list is empty if no"},{"type":"text","text":" "},{"type":"text","text":"articles matched the query, and a maximum of 3 articles can be returned."}],"kind":"symbol","metadata":{"modules":[{"name":"AnswerBotProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"getDeflectionForQueryWithQuery:callback:"}],"role":"symbol","title":"getDeflectionForQuery(query:callback:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDeflectionForQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"query"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"DeflectionResponse","preciseIdentifier":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKDeflectionResponse"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"symbolKind":"method","externalID":"c:@CM@AnswerBotProvidersSDK@objc(cs)ZDKAnswerBotProvider(im)getDeflectionForQueryWithQuery:callback:","extendedModule":"AnswerBotProvidersSDK","platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvider"]]},"references":{"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotProvider":{"role":"symbol","title":"AnswerBotProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnswerBotProvider"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AnswerBotProvider"}],"url":"\/documentation\/answerbotproviderssdk\/answerbotprovider"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK":{"role":"collection","title":"AnswerBotProvidersSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK","kind":"symbol","type":"topic","url":"\/documentation\/answerbotproviderssdk"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/DeflectionResponse":{"role":"symbol","title":"DeflectionResponse","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeflectionResponse"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionResponse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeflectionResponse"}],"url":"\/documentation\/answerbotproviderssdk\/deflectionresponse"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotProvider/getDeflectionForQuery(query:callback:)-5i9ze":{"role":"symbol","title":"getDeflectionForQuery(query:callback:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDeflectionForQuery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"query"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"DeflectionResponse","preciseIdentifier":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKDeflectionResponse"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Gets a DeflectionResponse for the given query String. The DeflectionResponse"},{"type":"text","text":" "},{"type":"text","text":"contains an array of DeflectionArticles that match the query. The list is empty if no"},{"type":"text","text":" "},{"type":"text","text":"articles matched the query, and a maximum of 3 articles can be returned."}],"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvider\/getDeflectionForQuery(query:callback:)-5i9ze","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getDeflectionForQueryWithQuery:callback:"}],"url":"\/documentation\/answerbotproviderssdk\/answerbotprovider\/getdeflectionforquery(query:callback:)-5i9ze"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getDeflectionForQueryWithQuery:callback:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getDeflectionForQueryWithQuery:callback:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getDeflectionForQueryWithQuery:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"query"},{"kind":"text","text":" "},{"kind":"identifier","text":"callback:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(ZDKDeflectionResponse *, NSError *)","preciseIdentifier":"c:BFv(#*$@M@AnswerBotProvidersSDK@objc(cs)ZDKDeflectionResponse#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"callback"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotProvider\/title","value":"ZDKAnswerBotProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotProvider\/fragments","value":[{"kind":"identifier","text":"ZDKAnswerBotProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1DeflectionResponse\/title","value":"ZDKDeflectionResponse"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1DeflectionResponse\/fragments","value":[{"kind":"identifier","text":"ZDKDeflectionResponse"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotProvider~1getDeflectionForQuery(query:callback:)-5i9ze\/title","value":"getDeflectionForQueryWithQuery:callback:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotProvider~1getDeflectionForQuery(query:callback:)-5i9ze\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getDeflectionForQueryWithQuery:callback:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}