{"hierarchy":{"paths":[["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBot"]]},"variants":[{"paths":["\/documentation\/answerbotproviderssdk\/answerbot\/instance"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/answerbotproviderssdk\/answerbot\/instance"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"instance"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AnswerBot","preciseIdentifier":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKAnswerBot","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBot"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"AnswerBotProvidersSDK"}],"symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"instance","kind":"identifier"}],"roleHeading":"Type Property","title":"instance","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"instance","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKAnswerBot","text":"AnswerBot"},{"text":"?","kind":"text"}],"externalID":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKAnswerBot(cpy)instance"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBot\/instance"},"abstract":[{"type":"text","text":"Returns an instance of "},{"type":"codeVoice","code":"AnswerBot"},{"type":"text","text":" (singleton)"}],"sections":[],"kind":"symbol","references":{"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK":{"abstract":[],"title":"AnswerBotProvidersSDK","role":"collection","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK","url":"\/documentation\/answerbotproviderssdk","type":"topic","kind":"symbol"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBot":{"navigatorTitle":[{"kind":"identifier","text":"AnswerBot"}],"type":"topic","url":"\/documentation\/answerbotproviderssdk\/answerbot","role":"symbol","title":"AnswerBot","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AnswerBot"}],"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBot","abstract":[{"type":"text","text":"ZDKAnswerBot is responsible for initialization of"},{"type":"text","text":" "},{"type":"text","text":"the SDK and manages the backend configuration."}],"kind":"symbol"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBot/instance":{"navigatorTitle":[{"kind":"identifier","text":"instance"}],"type":"topic","url":"\/documentation\/answerbotproviderssdk\/answerbot\/instance","role":"symbol","title":"instance","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"instance","kind":"identifier"},{"kind":"text","text":": "},{"text":"AnswerBot","kind":"typeIdentifier","preciseIdentifier":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKAnswerBot"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBot\/instance","abstract":[{"type":"text","text":"Returns an instance of "},{"type":"codeVoice","code":"AnswerBot"},{"type":"text","text":" (singleton)"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"value":"instance","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"instance"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBot","text":"ZDKAnswerBot","preciseIdentifier":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKAnswerBot","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"instance","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBot\/title","op":"replace","value":"ZDKAnswerBot"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBot\/fragments","value":[{"kind":"identifier","text":"ZDKAnswerBot"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBot~1instance\/title","value":"instance"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBot~1instance\/fragments","value":[{"text":"instance","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}