{"metadata":{"symbolKind":"method","roleHeading":"Type Method","externalID":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKAnswerBot(cm)initializeWithZendesk:support:","modules":[{"name":"AnswerBotProvidersSDK"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"kind":"text","text":"("},{"text":"withZendesk","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Zendesk","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicZendesk"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"support"},{"text":": ","kind":"text"},{"text":"Support","kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKSupport"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initializeWithZendesk:support:","kind":"identifier"}],"title":"initialize(withZendesk:support:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/answerbotproviderssdk\/answerbot\/initialize(withzendesk:support:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/answerbotproviderssdk\/answerbot\/initialize(withzendesk:support:)"]}],"kind":"symbol","abstract":[{"text":"Initializes AnswerBot with Zendesk instance and Support - e.g. AnswerBot.initialize(withZendesk: Zendesk.instance, support: Support.instance!)","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBot"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"text":"withZendesk","kind":"externalParam"},{"kind":"text","text":" "},{"text":"zendesk","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicZendesk","kind":"typeIdentifier","text":"Zendesk"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"support"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Support","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKSupport"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"name":"zendesk","content":[{"inlineContent":[{"type":"text","text":"An instance of "},{"type":"codeVoice","code":"ZDKClassicZendesk"},{"type":"text","text":"."}],"type":"paragraph"}]},{"name":"support","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An instance of "},{"type":"codeVoice","code":"ZDKSupport"},{"type":"text","text":"."}]}]}]}],"identifier":{"url":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBot\/initialize(withZendesk:support:)","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK":{"title":"AnswerBotProvidersSDK","kind":"symbol","url":"\/documentation\/answerbotproviderssdk","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK","type":"topic"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBot":{"url":"\/documentation\/answerbotproviderssdk\/answerbot","kind":"symbol","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBot","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AnswerBot"}],"title":"AnswerBot","abstract":[{"type":"text","text":"ZDKAnswerBot is responsible for initialization of"},{"type":"text","text":" "},{"type":"text","text":"the SDK and manages the backend configuration."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"AnswerBot"}],"role":"symbol"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBot/initialize(withZendesk:support:)":{"title":"initialize(withZendesk:support:)","url":"\/documentation\/answerbotproviderssdk\/answerbot\/initialize(withzendesk:support:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialize"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withZendesk"},{"text":": ","kind":"text"},{"text":"Zendesk","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicZendesk"},{"kind":"text","text":"?, "},{"text":"support","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Support","kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKSupport"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBot\/initialize(withZendesk:support:)","role":"symbol","abstract":[{"type":"text","text":"Initializes AnswerBot with Zendesk instance and Support - e.g. AnswerBot.initialize(withZendesk: Zendesk.instance, support: Support.instance!)"}],"navigatorTitle":[{"kind":"identifier","text":"initializeWithZendesk:support:"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"value":"initializeWithZendesk:support:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"initializeWithZendesk:support:"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initializeWithZendesk:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ZDKClassicZendesk","preciseIdentifier":"c:objc(cs)ZDKClassicZendesk"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"zendesk"},{"kind":"text","text":" "},{"kind":"identifier","text":"support:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"ZDKSupport","preciseIdentifier":"c:objc(cs)ZDKSupport"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"support"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBot\/title","value":"ZDKAnswerBot","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBot\/fragments","value":[{"kind":"identifier","text":"ZDKAnswerBot"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBot~1initialize(withZendesk:support:)\/title","value":"initializeWithZendesk:support:"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBot~1initialize(withZendesk:support:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"initializeWithZendesk:support:"}]}]}]}