{"kind":"symbol","topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBot","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotDispatcherResponse","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvider","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettings","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettingsProvider","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/Deflection","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionArticle","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionResponse"]},{"identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProviderProtocol","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettingsProviderProtocol"],"title":"Protocols"},{"title":"Type Aliases","identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotDeflectionCallback","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProviderCallBack"]},{"identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/RejectionReason"],"title":"Enumerations"}],"hierarchy":{"paths":[[]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/answerbotproviderssdk"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/answerbotproviderssdk"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK"},"sections":[],"metadata":{"externalID":"AnswerBotProvidersSDK","roleHeading":"Framework","symbolKind":"module","modules":[{"name":"AnswerBotProvidersSDK"}],"role":"collection","title":"AnswerBotProvidersSDK"},"references":{"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotDeflectionCallback":{"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotDeflectionCallback","abstract":[],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"AnswerBotDeflectionCallback","kind":"identifier"}],"type":"topic","url":"\/documentation\/answerbotproviderssdk\/answerbotdeflectioncallback","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"AnswerBotDeflectionCallback","kind":"identifier"}],"title":"AnswerBotDeflectionCallback"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotProviderCallBack":{"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProviderCallBack","url":"\/documentation\/answerbotproviderssdk\/answerbotprovidercallback","title":"AnswerBotProviderCallBack","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AnswerBotProviderCallBack"}],"navigatorTitle":[{"text":"AnswerBotProviderCallBack","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/DeflectionResponse":{"title":"DeflectionResponse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeflectionResponse"}],"url":"\/documentation\/answerbotproviderssdk\/deflectionresponse","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DeflectionResponse","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionResponse"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotSettings":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AnswerBotSettings"}],"title":"AnswerBotSettings","kind":"symbol","url":"\/documentation\/answerbotproviderssdk\/answerbotsettings","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettings","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnswerBotSettings"}],"abstract":[{"text":"The AnswerBot Settings model","type":"text"}]},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotDispatcherResponse":{"title":"AnswerBotDispatcherResponse","navigatorTitle":[{"text":"AnswerBotDispatcherResponse","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/answerbotproviderssdk\/answerbotdispatcherresponse","abstract":[],"role":"symbol","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotDispatcherResponse","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AnswerBotDispatcherResponse"}]},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotProvider":{"type":"topic","url":"\/documentation\/answerbotproviderssdk\/answerbotprovider","kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvider","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AnswerBotProvider"}],"title":"AnswerBotProvider","navigatorTitle":[{"text":"AnswerBotProvider","kind":"identifier"}]},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotProvidersSDKVersionString":{"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvidersSDKVersionString","fragments":[{"kind":"identifier","text":"AnswerBotProvidersSDKVersionString"}],"type":"topic","kind":"symbol","title":"AnswerBotProvidersSDKVersionString","role":"symbol","url":"\/documentation\/answerbotproviderssdk\/answerbotproviderssdkversionstring","abstract":[{"text":"Project version string for AnswerBotProvidersSDK.","type":"text"}]},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/Deflection":{"type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Deflection","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/Deflection","role":"symbol","navigatorTitle":[{"text":"Deflection","kind":"identifier"}],"title":"Deflection","url":"\/documentation\/answerbotproviderssdk\/deflection"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBot":{"url":"\/documentation\/answerbotproviderssdk\/answerbot","kind":"symbol","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBot","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AnswerBot"}],"title":"AnswerBot","abstract":[{"type":"text","text":"ZDKAnswerBot is responsible for initialization of"},{"type":"text","text":" "},{"type":"text","text":"the SDK and manages the backend configuration."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"AnswerBot"}],"role":"symbol"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotProvidersSDKVersionNumber":{"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvidersSDKVersionNumber","fragments":[{"kind":"identifier","text":"AnswerBotProvidersSDKVersionNumber"}],"type":"topic","kind":"symbol","title":"AnswerBotProvidersSDKVersionNumber","role":"symbol","url":"\/documentation\/answerbotproviderssdk\/answerbotproviderssdkversionnumber","abstract":[{"text":"Project version number for AnswerBotProvidersSDK.","type":"text"}]},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/RejectionReason":{"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/RejectionReason","kind":"symbol","type":"topic","navigatorTitle":[{"text":"RejectionReason","kind":"identifier"}],"abstract":[],"role":"symbol","url":"\/documentation\/answerbotproviderssdk\/rejectionreason","title":"RejectionReason","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"RejectionReason","kind":"identifier"}]},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotProviderProtocol":{"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProviderProtocol","title":"AnswerBotProviderProtocol","url":"\/documentation\/answerbotproviderssdk\/answerbotproviderprotocol","abstract":[],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AnswerBotProviderProtocol","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AnswerBotProviderProtocol"}],"kind":"symbol","role":"symbol"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK":{"title":"AnswerBotProvidersSDK","kind":"symbol","url":"\/documentation\/answerbotproviderssdk","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK","type":"topic"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/DeflectionArticle":{"title":"DeflectionArticle","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionArticle","url":"\/documentation\/answerbotproviderssdk\/deflectionarticle","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DeflectionArticle"}],"type":"topic","abstract":[],"navigatorTitle":[{"text":"DeflectionArticle","kind":"identifier"}]},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotSettingsProviderProtocol":{"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettingsProviderProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnswerBotSettingsProviderProtocol"}],"kind":"symbol","title":"AnswerBotSettingsProviderProtocol","navigatorTitle":[{"kind":"identifier","text":"AnswerBotSettingsProviderProtocol"}],"url":"\/documentation\/answerbotproviderssdk\/answerbotsettingsproviderprotocol","abstract":[],"role":"symbol","type":"topic"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotSettingsProvider":{"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettingsProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnswerBotSettingsProvider"}],"kind":"symbol","title":"AnswerBotSettingsProvider","navigatorTitle":[{"kind":"identifier","text":"AnswerBotSettingsProvider"}],"url":"\/documentation\/answerbotproviderssdk\/answerbotsettingsprovider","abstract":[],"role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/topicSections","op":"replace","value":[{"title":"Classes","identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBot","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotDispatcherResponse","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvider","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettings","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettingsProvider","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/Deflection","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionArticle","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionResponse"]},{"identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvidersSDKVersionNumber","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvidersSDKVersionString"],"title":"Variables"},{"identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/RejectionReason"],"title":"Enumerations"}]},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":"ZDKDeflectionResponse","op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1DeflectionResponse\/title"},{"value":[{"text":"ZDKDeflectionResponse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1DeflectionResponse\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotSettings\/title","value":"ZDKAnswerBotSettings","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotSettings\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKAnswerBotSettings"}]},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotDispatcherResponse\/title","value":"ZDKAnswerBotDispatcherResponse","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKAnswerBotDispatcherResponse"}],"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotDispatcherResponse\/fragments"},{"value":"ZDKAnswerBotProvider","op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotProvider\/title"},{"value":[{"text":"ZDKAnswerBotProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotProvider\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1Deflection\/title","op":"replace","value":"ZDKDeflection"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1Deflection\/fragments","value":[{"text":"ZDKDeflection","kind":"identifier"}]},{"value":"ZDKAnswerBot","op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBot\/title"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBot\/fragments","op":"replace","value":[{"text":"ZDKAnswerBot","kind":"identifier"}]},{"value":"ZDKRejectionReason","op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1RejectionReason\/title"},{"value":[{"text":"ZDKRejectionReason","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1RejectionReason\/fragments"},{"value":"ZDKDeflectionArticle","op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1DeflectionArticle\/title"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1DeflectionArticle\/fragments","value":[{"text":"ZDKDeflectionArticle","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"ZDKAnswerBotSettingsProvider","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotSettingsProvider\/title"},{"value":[{"text":"ZDKAnswerBotSettingsProvider","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotSettingsProvider\/fragments"}]}]}