{"hierarchy":{"paths":[["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionArticle"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/answerbotproviderssdk\/deflectionarticle\/snippet"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/answerbotproviderssdk\/deflectionarticle\/snippet"]}],"identifier":{"url":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionArticle\/snippet","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"snippet"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"snippet","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKDeflectionArticle(py)snippet","navigatorTitle":[{"text":"snippet","kind":"identifier"}],"title":"snippet","symbolKind":"property","modules":[{"name":"AnswerBotProvidersSDK"}]},"references":{"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK":{"title":"AnswerBotProvidersSDK","kind":"symbol","url":"\/documentation\/answerbotproviderssdk","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK","type":"topic"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/DeflectionArticle":{"title":"DeflectionArticle","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionArticle","url":"\/documentation\/answerbotproviderssdk\/deflectionarticle","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DeflectionArticle"}],"type":"topic","abstract":[],"navigatorTitle":[{"text":"DeflectionArticle","kind":"identifier"}]},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/DeflectionArticle/snippet":{"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionArticle\/snippet","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"snippet"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol","url":"\/documentation\/answerbotproviderssdk\/deflectionarticle\/snippet","type":"topic","kind":"symbol","title":"snippet","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"snippet"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"snippet","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"snippet","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"snippet"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"ZDKDeflectionArticle","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1DeflectionArticle\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1DeflectionArticle\/fragments","value":[{"kind":"identifier","text":"ZDKDeflectionArticle"}]},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1DeflectionArticle~1snippet\/title","value":"snippet","op":"replace"},{"value":[{"kind":"identifier","text":"snippet"}],"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1DeflectionArticle~1snippet\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}