{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deflectionArticles"},{"text":": [","kind":"text"},{"text":"DeflectionArticle","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionArticle","preciseIdentifier":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKDeflectionArticle"},{"kind":"text","text":"]"}]}]}],"variants":[{"paths":["\/documentation\/answerbotproviderssdk\/deflectionresponse\/deflectionarticles"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/answerbotproviderssdk\/deflectionresponse\/deflectionarticles"]}],"metadata":{"navigatorTitle":[{"text":"deflectionArticles","kind":"identifier"}],"title":"deflectionArticles","modules":[{"name":"AnswerBotProvidersSDK"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deflectionArticles","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKDeflectionArticle","text":"DeflectionArticle"},{"kind":"text","text":"]"}],"externalID":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKDeflectionResponse(py)deflectionArticles","roleHeading":"Instance Property","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionResponse"]]},"identifier":{"url":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionResponse\/deflectionArticles","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/DeflectionArticle":{"url":"\/documentation\/answerbotproviderssdk\/deflectionarticle","type":"topic","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionArticle","kind":"symbol","title":"DeflectionArticle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeflectionArticle"}],"navigatorTitle":[{"text":"DeflectionArticle","kind":"identifier"}],"role":"symbol","abstract":[]},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/DeflectionResponse":{"type":"topic","kind":"symbol","url":"\/documentation\/answerbotproviderssdk\/deflectionresponse","title":"DeflectionResponse","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionResponse","navigatorTitle":[{"kind":"identifier","text":"DeflectionResponse"}],"abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeflectionResponse","kind":"identifier"}]},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK":{"type":"topic","kind":"symbol","url":"\/documentation\/answerbotproviderssdk","title":"AnswerBotProvidersSDK","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK","abstract":[],"role":"collection"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/DeflectionResponse/deflectionArticles":{"type":"topic","kind":"symbol","url":"\/documentation\/answerbotproviderssdk\/deflectionresponse\/deflectionarticles","title":"deflectionArticles","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/DeflectionResponse\/deflectionArticles","navigatorTitle":[{"kind":"identifier","text":"deflectionArticles"}],"abstract":[],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"deflectionArticles","kind":"identifier"},{"text":": [","kind":"text"},{"text":"DeflectionArticle","kind":"typeIdentifier","preciseIdentifier":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKDeflectionArticle"},{"kind":"text","text":"]"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"deflectionArticles","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"deflectionArticles","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<ZDKDeflectionArticle *>","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"deflectionArticles"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"ZDKDeflectionArticle","op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1DeflectionArticle\/title"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1DeflectionArticle\/fragments","value":[{"kind":"identifier","text":"ZDKDeflectionArticle"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1DeflectionResponse\/title","value":"ZDKDeflectionResponse"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKDeflectionResponse"}],"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1DeflectionResponse\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1DeflectionResponse~1deflectionArticles\/title","value":"deflectionArticles"},{"op":"replace","value":[{"kind":"identifier","text":"deflectionArticles"}],"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1DeflectionResponse~1deflectionArticles\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}