{"kind":"symbol","variants":[{"paths":["\/documentation\/answerbotproviderssdk\/answerbotprovider\/rejectwitharticle(deflectionid:articleid:interactionaccesstoken:reason:callback:)-1q47a"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/answerbotproviderssdk\/answerbotprovider\/rejectwitharticle(deflectionid:articleid:interactionaccesstoken:reason:callback:)-1q47a"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvider"]]},"abstract":[{"type":"text","text":"Marks a deflection article as unhelpful and indicates that it did not resolve the user’s issue"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rejectWithArticle"},{"kind":"text","text":"("},{"kind":"externalParam","text":"deflectionId"},{"text":": ","kind":"text"},{"text":"Int64","preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"articleId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"interactionAccessToken","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"text":"RejectionReason","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/RejectionReason","preciseIdentifier":"c:@M@AnswerBotProvidersSDK@E@ZDKRejectionReason"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callback"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ((","kind":"text"},{"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotDispatcherResponse","kind":"typeIdentifier","preciseIdentifier":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKAnswerBotDispatcherResponse","text":"AnswerBotDispatcherResponse"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":"))"}]}]},{"kind":"parameters","parameters":[{"name":"deflectionId","content":[{"type":"paragraph","inlineContent":[{"text":"The deflectionId","type":"text"}]}]},{"name":"articleId","content":[{"type":"paragraph","inlineContent":[{"text":"The articleId that did not resolve the users issue","type":"text"}]}]},{"name":"interactionAccessToken","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"InteractionAccessToken from DeflectionResponse"}]}]},{"content":[{"inlineContent":[{"text":"The Reason the article was not helpful","type":"text"}],"type":"paragraph"}],"name":"reason"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Callback that will deliver the result"}]}],"name":"callback"}]}],"identifier":{"url":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvider\/rejectWithArticle(deflectionId:articleId:interactionAccessToken:reason:callback:)-1q47a","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"rejectWithArticle","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"deflectionId"},{"kind":"text","text":": "},{"text":"Int64","preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"articleId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"interactionAccessToken"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"reason"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"RejectionReason","preciseIdentifier":"c:@M@AnswerBotProvidersSDK@E@ZDKRejectionReason"},{"text":", ","kind":"text"},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"AnswerBotDispatcherResponse","preciseIdentifier":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKAnswerBotDispatcherResponse"},{"text":"?, ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":"))"}],"externalID":"c:@CM@AnswerBotProvidersSDK@objc(cs)ZDKAnswerBotProvider(im)rejectWithArticleWithDeflectionId:articleId:interactionAccessToken:reason:callback:","symbolKind":"method","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"AnswerBotProvidersSDK"}],"platforms":[],"title":"rejectWithArticle(deflectionId:articleId:interactionAccessToken:reason:callback:)","navigatorTitle":[{"text":"rejectWithArticleWithDeflectionId:articleId:interactionAccessToken:reason:callback:","kind":"identifier"}]},"sections":[],"references":{"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotDispatcherResponse":{"url":"\/documentation\/answerbotproviderssdk\/answerbotdispatcherresponse","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotDispatcherResponse","type":"topic","kind":"symbol","title":"AnswerBotDispatcherResponse","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnswerBotDispatcherResponse"}],"navigatorTitle":[{"text":"AnswerBotDispatcherResponse","kind":"identifier"}],"role":"symbol","abstract":[]},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK":{"type":"topic","kind":"symbol","url":"\/documentation\/answerbotproviderssdk","title":"AnswerBotProvidersSDK","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK","abstract":[],"role":"collection"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotProvider":{"role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/answerbotproviderssdk\/answerbotprovider","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvider","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AnswerBotProvider","kind":"identifier"}],"title":"AnswerBotProvider","navigatorTitle":[{"kind":"identifier","text":"AnswerBotProvider"}]},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/RejectionReason":{"role":"symbol","url":"\/documentation\/answerbotproviderssdk\/rejectionreason","navigatorTitle":[{"text":"RejectionReason","kind":"identifier"}],"title":"RejectionReason","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RejectionReason"}],"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/RejectionReason","kind":"symbol","type":"topic"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotProvider/rejectWithArticle(deflectionId:articleId:interactionAccessToken:reason:callback:)-1q47a":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rejectWithArticle","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"deflectionId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"text":"articleId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int64","preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"interactionAccessToken","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"reason","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@AnswerBotProvidersSDK@E@ZDKRejectionReason","kind":"typeIdentifier","text":"RejectionReason"},{"text":", ","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"AnswerBotDispatcherResponse","preciseIdentifier":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKAnswerBotDispatcherResponse","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":"))"}],"navigatorTitle":[{"kind":"identifier","text":"rejectWithArticleWithDeflectionId:articleId:interactionAccessToken:reason:callback:"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Marks a deflection article as unhelpful and indicates that it did not resolve the user’s issue"}],"title":"rejectWithArticle(deflectionId:articleId:interactionAccessToken:reason:callback:)","url":"\/documentation\/answerbotproviderssdk\/answerbotprovider\/rejectwitharticle(deflectionid:articleid:interactionaccesstoken:reason:callback:)-1q47a","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvider\/rejectWithArticle(deflectionId:articleId:interactionAccessToken:reason:callback:)-1q47a","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"rejectWithArticleWithDeflectionId:articleId:interactionAccessToken:reason:callback:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"rejectWithArticleWithDeflectionId:articleId:interactionAccessToken:reason:callback:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"rejectWithArticleWithDeflectionId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"int64_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@int64_t"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"deflectionId"},{"text":" ","kind":"text"},{"text":"articleId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"int64_t","preciseIdentifier":"c:@T@int64_t"},{"kind":"text","text":") "},{"text":"articleId","kind":"internalParam"},{"kind":"text","text":" "},{"text":"interactionAccessToken:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"interactionAccessToken","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"reason:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@AnswerBotProvidersSDK@E@ZDKRejectionReason","text":"ZDKRejectionReason","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/RejectionReason"},{"kind":"text","text":") "},{"text":"reason","kind":"internalParam"},{"kind":"text","text":" "},{"text":"callback:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$@M@AnswerBotProvidersSDK@objc(cs)ZDKAnswerBotDispatcherResponse#*$objc(cs)NSError)","text":"void (^)(ZDKAnswerBotDispatcherResponse *, NSError *)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"callback"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotDispatcherResponse\/title","value":"ZDKAnswerBotDispatcherResponse"},{"value":[{"kind":"identifier","text":"ZDKAnswerBotDispatcherResponse"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotDispatcherResponse\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotProvider\/title","value":"ZDKAnswerBotProvider"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotProvider\/fragments","value":[{"kind":"identifier","text":"ZDKAnswerBotProvider"}],"op":"replace"},{"value":"ZDKRejectionReason","op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1RejectionReason\/title"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1RejectionReason\/fragments","value":[{"kind":"identifier","text":"ZDKRejectionReason"}],"op":"replace"},{"value":"rejectWithArticleWithDeflectionId:articleId:interactionAccessToken:reason:callback:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotProvider~1rejectWithArticle(deflectionId:articleId:interactionAccessToken:reason:callback:)-1q47a\/title"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotProvider~1rejectWithArticle(deflectionId:articleId:interactionAccessToken:reason:callback:)-1q47a\/fragments","value":[{"kind":"text","text":"- "},{"text":"rejectWithArticleWithDeflectionId:articleId:interactionAccessToken:reason:callback:","kind":"identifier"}],"op":"replace"}]}]}