{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvider\/rejectWithArticle(deflectionId:articleId:interactionAccessToken:reason:callback:)-1wagu"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rejectWithArticle","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"deflectionId"},{"kind":"text","text":": "},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"},{"text":", ","kind":"text"},{"text":"articleId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"text":"interactionAccessToken","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RejectionReason","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/RejectionReason","preciseIdentifier":"c:@M@AnswerBotProvidersSDK@E@ZDKRejectionReason"},{"kind":"text","text":" = .unknown, "},{"kind":"externalParam","text":"callback"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:21AnswerBotProvidersSDK0aB16ProviderCallBacka","text":"AnswerBotProviderCallBack","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProviderCallBack"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"deflectionId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The deflectionId"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The articleId that did not resolve the users issue"}],"type":"paragraph"}],"name":"articleId"},{"content":[{"type":"paragraph","inlineContent":[{"text":"InteractionAccessToken from DeflectionResponse","type":"text"}]}],"name":"interactionAccessToken"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The Reason the article was not helpful"}]}],"name":"reason"},{"name":"callback","content":[{"type":"paragraph","inlineContent":[{"text":"Callback that will deliver the result","type":"text"}]}]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/answerbotproviderssdk\/answerbotprovider\/rejectwitharticle(deflectionid:articleid:interactionaccesstoken:reason:callback:)-1wagu"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvider"]]},"metadata":{"role":"symbol","title":"rejectWithArticle(deflectionId:articleId:interactionAccessToken:reason:callback:)","modules":[{"name":"AnswerBotProvidersSDK"}],"symbolKind":"method","externalID":"s:21AnswerBotProvidersSDK0aB8ProviderC17rejectWithArticle12deflectionId07articleJ022interactionAccessToken6reason8callbackys5Int64V_AKSSAA15RejectionReasonOys6ResultOyAA0aB18DispatcherResponseCs5Error_pGctF","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rejectWithArticle","kind":"identifier"},{"text":"(","kind":"text"},{"text":"deflectionId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"articleId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"interactionAccessToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"reason","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RejectionReason","kind":"typeIdentifier","preciseIdentifier":"c:@M@AnswerBotProvidersSDK@E@ZDKRejectionReason"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callback"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:21AnswerBotProvidersSDK0aB16ProviderCallBacka","kind":"typeIdentifier","text":"AnswerBotProviderCallBack"},{"text":")","kind":"text"}],"roleHeading":"Instance Method"},"abstract":[{"type":"text","text":"Marks a deflection article as unhelpful and indicates that it did not resolve the user’s issue"}],"references":{"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotProvider":{"kind":"symbol","role":"symbol","url":"\/documentation\/answerbotproviderssdk\/answerbotprovider","type":"topic","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvider","navigatorTitle":[{"text":"AnswerBotProvider","kind":"identifier"}],"title":"AnswerBotProvider","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AnswerBotProvider","kind":"identifier"}],"abstract":[]},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotProvider/rejectWithArticle(deflectionId:articleId:interactionAccessToken:reason:callback:)-1wagu":{"type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"Marks a deflection article as unhelpful and indicates that it did not resolve the user’s issue","type":"text"}],"title":"rejectWithArticle(deflectionId:articleId:interactionAccessToken:reason:callback:)","url":"\/documentation\/answerbotproviderssdk\/answerbotprovider\/rejectwitharticle(deflectionid:articleid:interactionaccesstoken:reason:callback:)-1wagu","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvider\/rejectWithArticle(deflectionId:articleId:interactionAccessToken:reason:callback:)-1wagu","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rejectWithArticle","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"deflectionId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V","text":"Int64"},{"kind":"text","text":", "},{"text":"articleId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"interactionAccessToken"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"reason","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RejectionReason","kind":"typeIdentifier","preciseIdentifier":"c:@M@AnswerBotProvidersSDK@E@ZDKRejectionReason"},{"kind":"text","text":", "},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:21AnswerBotProvidersSDK0aB16ProviderCallBacka","text":"AnswerBotProviderCallBack","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK":{"abstract":[],"title":"AnswerBotProvidersSDK","role":"collection","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK","url":"\/documentation\/answerbotproviderssdk","type":"topic","kind":"symbol"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/RejectionReason":{"url":"\/documentation\/answerbotproviderssdk\/rejectionreason","navigatorTitle":[{"kind":"identifier","text":"RejectionReason"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/RejectionReason","abstract":[],"kind":"symbol","type":"topic","title":"RejectionReason","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RejectionReason","kind":"identifier"}]},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotProviderCallBack":{"url":"\/documentation\/answerbotproviderssdk\/answerbotprovidercallback","navigatorTitle":[{"kind":"identifier","text":"AnswerBotProviderCallBack"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProviderCallBack","abstract":[],"kind":"symbol","type":"topic","title":"AnswerBotProviderCallBack","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AnswerBotProviderCallBack","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"ZDKAnswerBotProvider","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotProvider\/title"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotProvider\/fragments","value":[{"text":"ZDKAnswerBotProvider","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1RejectionReason\/title","value":"ZDKRejectionReason"},{"value":[{"text":"ZDKRejectionReason","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1RejectionReason\/fragments"}]}]}