{"abstract":[{"text":"Marks a DeflectionArticle as helpful and indicates that the article successfully","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"resolved the users issue."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvider"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvider\/resolveWithArticle(deflectionId:articleId:interactionAccessToken:callback:)-3e2nr","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@CM@AnswerBotProvidersSDK@objc(cs)ZDKAnswerBotProvider(im)resolveWithArticleWithDeflectionId:articleId:interactionAccessToken:callback:","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resolveWithArticle"},{"text":"(","kind":"text"},{"text":"deflectionId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"articleId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"interactionAccessToken"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKAnswerBotDispatcherResponse","text":"AnswerBotDispatcherResponse"},{"text":"?, ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":"))","kind":"text"}],"platforms":[],"modules":[{"name":"AnswerBotProvidersSDK"}],"title":"resolveWithArticle(deflectionId:articleId:interactionAccessToken:callback:)","navigatorTitle":[{"text":"resolveWithArticleWithDeflectionId:articleId:interactionAccessToken:callback:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","extendedModule":"AnswerBotProvidersSDK"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resolveWithArticle","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"deflectionId"},{"text":": ","kind":"text"},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"articleId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V","text":"Int64"},{"text":", ","kind":"text"},{"text":"interactionAccessToken","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" (("},{"preciseIdentifier":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKAnswerBotDispatcherResponse","kind":"typeIdentifier","text":"AnswerBotDispatcherResponse","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotDispatcherResponse"},{"text":"?, ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":"))"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"deflectionId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the deflectionId"}]}]},{"name":"articleId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the articleId that successfully resolved the users issue."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"InteractionAccessToken from DeflectionResponse"}]}],"name":"interactionAccessToken"},{"name":"callback","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Callback that will deliver result"}]}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/answerbotproviderssdk\/answerbotprovider\/resolvewitharticle(deflectionid:articleid:interactionaccesstoken:callback:)-3e2nr"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/answerbotproviderssdk\/answerbotprovider\/resolvewitharticle(deflectionid:articleid:interactionaccesstoken:callback:)-3e2nr"]}],"references":{"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotProvider":{"kind":"symbol","role":"symbol","url":"\/documentation\/answerbotproviderssdk\/answerbotprovider","type":"topic","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvider","navigatorTitle":[{"text":"AnswerBotProvider","kind":"identifier"}],"title":"AnswerBotProvider","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AnswerBotProvider","kind":"identifier"}],"abstract":[]},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotDispatcherResponse":{"title":"AnswerBotDispatcherResponse","abstract":[],"navigatorTitle":[{"text":"AnswerBotDispatcherResponse","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AnswerBotDispatcherResponse","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotDispatcherResponse","url":"\/documentation\/answerbotproviderssdk\/answerbotdispatcherresponse"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotProvider/resolveWithArticle(deflectionId:articleId:interactionAccessToken:callback:)-3e2nr":{"role":"symbol","abstract":[{"type":"text","text":"Marks a DeflectionArticle as helpful and indicates that the article successfully"},{"type":"text","text":" "},{"type":"text","text":"resolved the users issue."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvider\/resolveWithArticle(deflectionId:articleId:interactionAccessToken:callback:)-3e2nr","title":"resolveWithArticle(deflectionId:articleId:interactionAccessToken:callback:)","url":"\/documentation\/answerbotproviderssdk\/answerbotprovider\/resolvewitharticle(deflectionid:articleid:interactionaccesstoken:callback:)-3e2nr","navigatorTitle":[{"kind":"identifier","text":"resolveWithArticleWithDeflectionId:articleId:interactionAccessToken:callback:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resolveWithArticle","kind":"identifier"},{"text":"(","kind":"text"},{"text":"deflectionId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"articleId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V","text":"Int64"},{"text":", ","kind":"text"},{"text":"interactionAccessToken","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"callback"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKAnswerBotDispatcherResponse","text":"AnswerBotDispatcherResponse","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":"))","kind":"text"}]},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK":{"abstract":[],"title":"AnswerBotProvidersSDK","role":"collection","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK","url":"\/documentation\/answerbotproviderssdk","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"resolveWithArticleWithDeflectionId:articleId:interactionAccessToken:callback:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resolveWithArticleWithDeflectionId:articleId:interactionAccessToken:callback:"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"resolveWithArticleWithDeflectionId:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@int64_t","kind":"typeIdentifier","text":"int64_t"},{"kind":"text","text":") "},{"text":"deflectionId","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"articleId:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@int64_t","text":"int64_t","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"articleId"},{"kind":"text","text":" "},{"text":"interactionAccessToken:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"interactionAccessToken"},{"kind":"text","text":" "},{"text":"callback:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:BFv(#*$@M@AnswerBotProvidersSDK@objc(cs)ZDKAnswerBotDispatcherResponse#*$objc(cs)NSError)","kind":"typeIdentifier","text":"void (^)(ZDKAnswerBotDispatcherResponse *, NSError *)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"callback"},{"kind":"text","text":";"}]}]}},{"value":"ZDKAnswerBotProvider","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotProvider\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotProvider\/fragments","op":"replace","value":[{"text":"ZDKAnswerBotProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotDispatcherResponse\/title","value":"ZDKAnswerBotDispatcherResponse"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotDispatcherResponse\/fragments","value":[{"text":"ZDKAnswerBotDispatcherResponse","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotProvider~1resolveWithArticle(deflectionId:articleId:interactionAccessToken:callback:)-3e2nr\/title","value":"resolveWithArticleWithDeflectionId:articleId:interactionAccessToken:callback:"},{"value":[{"text":"- ","kind":"text"},{"text":"resolveWithArticleWithDeflectionId:articleId:interactionAccessToken:callback:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotProvider~1resolveWithArticle(deflectionId:articleId:interactionAccessToken:callback:)-3e2nr\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}