{"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getSettings"},{"text":"(","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettings","kind":"typeIdentifier","preciseIdentifier":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKAnswerBotSettings","text":"AnswerBotSettings"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"callback","content":[{"inlineContent":[{"type":"text","text":"A callback that takes a optional "},{"code":"AnswerBotSettings","type":"codeVoice"},{"text":" object","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettingsProvider"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettingsProvider\/getSettings(callback:)"},"abstract":[{"text":"Fetches an ","type":"text"},{"type":"codeVoice","code":"AnswerBotSettings"},{"text":" from the network\/local cache.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/answerbotproviderssdk\/answerbotsettingsprovider\/getsettings(callback:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/answerbotproviderssdk\/answerbotsettingsprovider\/getsettings(callback:)"]}],"metadata":{"modules":[{"name":"AnswerBotProvidersSDK"}],"role":"symbol","roleHeading":"Type Method","navigatorTitle":[{"text":"getSettingsWithCallback:","kind":"identifier"}],"externalID":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKAnswerBotSettingsProvider(cm)getSettingsWithCallback:","title":"getSettings(callback:)","symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getSettings","kind":"identifier"},{"text":"(","kind":"text"},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"AnswerBotSettings","preciseIdentifier":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKAnswerBotSettings"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotSettingsProvider":{"role":"symbol","title":"AnswerBotSettingsProvider","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AnswerBotSettingsProvider"}],"kind":"symbol","url":"\/documentation\/answerbotproviderssdk\/answerbotsettingsprovider","abstract":[],"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettingsProvider","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AnswerBotSettingsProvider","kind":"identifier"}]},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotSettings":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AnswerBotSettings"}],"type":"topic","role":"symbol","title":"AnswerBotSettings","kind":"symbol","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettings","url":"\/documentation\/answerbotproviderssdk\/answerbotsettings","abstract":[{"type":"text","text":"The AnswerBot Settings model"}],"navigatorTitle":[{"kind":"identifier","text":"AnswerBotSettings"}]},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotSettingsProvider/getSettings(callback:)":{"role":"symbol","title":"getSettings(callback:)","type":"topic","navigatorTitle":[{"text":"getSettingsWithCallback:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettingsProvider\/getSettings(callback:)","url":"\/documentation\/answerbotproviderssdk\/answerbotsettingsprovider\/getsettings(callback:)","abstract":[{"type":"text","text":"Fetches an "},{"code":"AnswerBotSettings","type":"codeVoice"},{"type":"text","text":" from the network\/local cache."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getSettings"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callback"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKAnswerBotSettings","text":"AnswerBotSettings"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK":{"abstract":[],"title":"AnswerBotProvidersSDK","role":"collection","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK","url":"\/documentation\/answerbotproviderssdk","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"getSettingsWithCallback:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"getSettingsWithCallback:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"getSettingsWithCallback:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$@M@AnswerBotProvidersSDK@objc(cs)ZDKAnswerBotSettings)","text":"void (^)(ZDKAnswerBotSettings *)"},{"text":") ","kind":"text"},{"text":"callback","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","value":"ZDKAnswerBotSettingsProvider","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotSettingsProvider\/title"},{"op":"replace","value":[{"text":"ZDKAnswerBotSettingsProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotSettingsProvider\/fragments"},{"value":"ZDKAnswerBotSettings","op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotSettings\/title"},{"op":"replace","value":[{"text":"ZDKAnswerBotSettings","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotSettings\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotSettingsProvider~1getSettings(callback:)\/title","op":"replace","value":"getSettingsWithCallback:"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotSettingsProvider~1getSettings(callback:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"getSettingsWithCallback:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}