{"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"AnswerBotProvidersSDK"}],"externalID":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKAnswerBotProvider","title":"AnswerBotProvider","role":"symbol","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AnswerBotProvider","kind":"identifier"}],"navigatorTitle":[{"text":"AnswerBotProvider","kind":"identifier"}],"symbolKind":"class"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvider\/getDeflectionForQuery(query:callback:)-2dkxz","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvider\/getDeflectionForQuery(query:callback:)-5i9ze","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvider\/rejectWithArticle(deflectionId:articleId:interactionAccessToken:reason:callback:)-1q47a","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvider\/rejectWithArticle(deflectionId:articleId:interactionAccessToken:reason:callback:)-1wagu","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvider\/resolveWithArticle(deflectionId:articleId:interactionAccessToken:callback:)-3e2nr","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvider\/resolveWithArticle(deflectionId:articleId:interactionAccessToken:callback:)-4o4ya"]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProviderProtocol","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/SQ","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/SH"]}],"variants":[{"paths":["\/documentation\/answerbotproviderssdk\/answerbotprovider"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/answerbotproviderssdk\/answerbotprovider"]}],"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvider","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKAnswerBotProvider) ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnswerBotProvider"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.zendesk.AnswerBotProvidersSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/SQ","title":"Swift.Equatable"},"doc://com.zendesk.AnswerBotProvidersSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/SH","title":"Swift.Hashable"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotProvider/resolveWithArticle(deflectionId:articleId:interactionAccessToken:callback:)-3e2nr":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resolveWithArticle"},{"kind":"text","text":"("},{"text":"deflectionId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"articleId"},{"text":": ","kind":"text"},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"},{"text":", ","kind":"text"},{"text":"interactionAccessToken","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": (("},{"text":"AnswerBotDispatcherResponse","kind":"typeIdentifier","preciseIdentifier":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKAnswerBotDispatcherResponse"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"resolveWithArticleWithDeflectionId:articleId:interactionAccessToken:callback:","kind":"identifier"}],"title":"resolveWithArticle(deflectionId:articleId:interactionAccessToken:callback:)","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvider\/resolveWithArticle(deflectionId:articleId:interactionAccessToken:callback:)-3e2nr","kind":"symbol","url":"\/documentation\/answerbotproviderssdk\/answerbotprovider\/resolvewitharticle(deflectionid:articleid:interactionaccesstoken:callback:)-3e2nr","abstract":[{"text":"Marks a DeflectionArticle as helpful and indicates that the article successfully","type":"text"},{"type":"text","text":" "},{"text":"resolved the users issue.","type":"text"}]},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK":{"abstract":[],"title":"AnswerBotProvidersSDK","kind":"symbol","url":"\/documentation\/answerbotproviderssdk","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK"},"doc://com.zendesk.AnswerBotProvidersSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.zendesk.AnswerBotProvidersSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotProvider/getDeflectionForQuery(query:callback:)-5i9ze":{"type":"topic","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvider\/getDeflectionForQuery(query:callback:)-5i9ze","kind":"symbol","role":"symbol","title":"getDeflectionForQuery(query:callback:)","abstract":[{"text":"Gets a DeflectionResponse for the given query String. The DeflectionResponse","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"contains an array of DeflectionArticles that match the query. The list is empty if no"},{"type":"text","text":" "},{"text":"articles matched the query, and a maximum of 3 articles can be returned.","type":"text"}],"url":"\/documentation\/answerbotproviderssdk\/answerbotprovider\/getdeflectionforquery(query:callback:)-5i9ze","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getDeflectionForQuery","kind":"identifier"},{"text":"(","kind":"text"},{"text":"query","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKDeflectionResponse","text":"DeflectionResponse"},{"text":"?, ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":"))"}],"navigatorTitle":[{"text":"getDeflectionForQueryWithQuery:callback:","kind":"identifier"}]},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotProviderProtocol":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AnswerBotProviderProtocol"}],"url":"\/documentation\/answerbotproviderssdk\/answerbotproviderprotocol","type":"topic","role":"symbol","title":"AnswerBotProviderProtocol","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProviderProtocol","navigatorTitle":[{"text":"AnswerBotProviderProtocol","kind":"identifier"}],"abstract":[]},"doc://com.zendesk.AnswerBotProvidersSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotProvider/rejectWithArticle(deflectionId:articleId:interactionAccessToken:reason:callback:)-1wagu":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"rejectWithArticle","kind":"identifier"},{"kind":"text","text":"("},{"text":"deflectionId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"},{"text":", ","kind":"text"},{"text":"articleId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"text":", ","kind":"text"},{"text":"interactionAccessToken","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"reason"},{"text":": ","kind":"text"},{"text":"RejectionReason","kind":"typeIdentifier","preciseIdentifier":"c:@M@AnswerBotProvidersSDK@E@ZDKRejectionReason"},{"text":", ","kind":"text"},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:21AnswerBotProvidersSDK0aB16ProviderCallBacka","text":"AnswerBotProviderCallBack","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"rejectWithArticle(deflectionId:articleId:interactionAccessToken:reason:callback:)","type":"topic","abstract":[{"type":"text","text":"Marks a deflection article as unhelpful and indicates that it did not resolve the user’s issue"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvider\/rejectWithArticle(deflectionId:articleId:interactionAccessToken:reason:callback:)-1wagu","url":"\/documentation\/answerbotproviderssdk\/answerbotprovider\/rejectwitharticle(deflectionid:articleid:interactionaccesstoken:reason:callback:)-1wagu","role":"symbol"},"doc://com.zendesk.AnswerBotProvidersSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/objc(cs)NSObject","title":"NSObject"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotProvider/rejectWithArticle(deflectionId:articleId:interactionAccessToken:reason:callback:)-1q47a":{"url":"\/documentation\/answerbotproviderssdk\/answerbotprovider\/rejectwitharticle(deflectionid:articleid:interactionaccesstoken:reason:callback:)-1q47a","navigatorTitle":[{"text":"rejectWithArticleWithDeflectionId:articleId:interactionAccessToken:reason:callback:","kind":"identifier"}],"title":"rejectWithArticle(deflectionId:articleId:interactionAccessToken:reason:callback:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rejectWithArticle","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"deflectionId"},{"text":": ","kind":"text"},{"text":"Int64","preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"articleId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"text":"interactionAccessToken","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"reason","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AnswerBotProvidersSDK@E@ZDKRejectionReason","text":"RejectionReason"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"callback"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKAnswerBotDispatcherResponse","text":"AnswerBotDispatcherResponse"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":"))","kind":"text"}],"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvider\/rejectWithArticle(deflectionId:articleId:interactionAccessToken:reason:callback:)-1q47a","abstract":[{"type":"text","text":"Marks a deflection article as unhelpful and indicates that it did not resolve the user’s issue"}],"role":"symbol"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotProvider/resolveWithArticle(deflectionId:articleId:interactionAccessToken:callback:)-4o4ya":{"url":"\/documentation\/answerbotproviderssdk\/answerbotprovider\/resolvewitharticle(deflectionid:articleid:interactionaccesstoken:callback:)-4o4ya","type":"topic","title":"resolveWithArticle(deflectionId:articleId:interactionAccessToken:callback:)","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvider\/resolveWithArticle(deflectionId:articleId:interactionAccessToken:callback:)-4o4ya","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resolveWithArticle"},{"kind":"text","text":"("},{"text":"deflectionId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"articleId"},{"kind":"text","text":": "},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"},{"text":", ","kind":"text"},{"text":"interactionAccessToken","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"callback","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AnswerBotProviderCallBack","kind":"typeIdentifier","preciseIdentifier":"s:21AnswerBotProvidersSDK0aB16ProviderCallBacka"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Marks a DeflectionArticle as helpful and indicates that the article successfully"},{"text":" ","type":"text"},{"type":"text","text":"resolved the users issue."}],"kind":"symbol"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotProvider":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnswerBotProvider"}],"title":"AnswerBotProvider","type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvider","url":"\/documentation\/answerbotproviderssdk\/answerbotprovider","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"AnswerBotProvider","kind":"identifier"}]},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotProvider/getDeflectionForQuery(query:callback:)-2dkxz":{"type":"topic","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvider\/getDeflectionForQuery(query:callback:)-2dkxz","kind":"symbol","role":"symbol","title":"getDeflectionForQuery(query:callback:)","abstract":[{"type":"text","text":"Gets a DeflectionResponse for the given query String. The DeflectionResponse"},{"type":"text","text":" "},{"text":"contains an array of DeflectionArticles that match the query. The list is empty if no","type":"text"},{"text":" ","type":"text"},{"text":"articles matched the query, and a maximum of 3 articles can be returned.","type":"text"}],"url":"\/documentation\/answerbotproviderssdk\/answerbotprovider\/getdeflectionforquery(query:callback:)-2dkxz","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getDeflectionForQuery","kind":"identifier"},{"kind":"text","text":"("},{"text":"query","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callback"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AnswerBotDeflectionCallback","preciseIdentifier":"s:21AnswerBotProvidersSDK0aB18DeflectionCallbacka"},{"text":")","kind":"text"}]},"doc://com.zendesk.AnswerBotProvidersSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"ZDKAnswerBotProvider","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ZDKAnswerBotProvider","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKAnswerBotProvider","kind":"identifier"}]},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvider\/getDeflectionForQuery(query:callback:)-5i9ze","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvider\/rejectWithArticle(deflectionId:articleId:interactionAccessToken:reason:callback:)-1q47a","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotProvider\/resolveWithArticle(deflectionId:articleId:interactionAccessToken:callback:)-3e2nr"]}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/objc(cs)NSObject"]}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKAnswerBotProvider","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotProvider~1resolveWithArticle(deflectionId:articleId:interactionAccessToken:callback:)-3e2nr\/title","op":"replace","value":"resolveWithArticleWithDeflectionId:articleId:interactionAccessToken:callback:"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotProvider~1resolveWithArticle(deflectionId:articleId:interactionAccessToken:callback:)-3e2nr\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"resolveWithArticleWithDeflectionId:articleId:interactionAccessToken:callback:"}],"op":"replace"},{"value":"getDeflectionForQueryWithQuery:callback:","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotProvider~1getDeflectionForQuery(query:callback:)-5i9ze\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getDeflectionForQueryWithQuery:callback:"}],"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotProvider~1getDeflectionForQuery(query:callback:)-5i9ze\/fragments"},{"op":"replace","value":"rejectWithArticleWithDeflectionId:articleId:interactionAccessToken:reason:callback:","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotProvider~1rejectWithArticle(deflectionId:articleId:interactionAccessToken:reason:callback:)-1q47a\/title"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotProvider~1rejectWithArticle(deflectionId:articleId:interactionAccessToken:reason:callback:)-1q47a\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"rejectWithArticleWithDeflectionId:articleId:interactionAccessToken:reason:callback:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotProvider\/title","op":"replace","value":"ZDKAnswerBotProvider"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotProvider\/fragments","value":[{"text":"ZDKAnswerBotProvider","kind":"identifier"}],"op":"replace"}]}]}