{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBot"},"metadata":{"roleHeading":"Class","title":"AnswerBot","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AnswerBot","kind":"identifier"}],"externalID":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKAnswerBot","modules":[{"name":"AnswerBotProvidersSDK"}],"navigatorTitle":[{"text":"AnswerBot","kind":"identifier"}],"symbolKind":"class"},"kind":"symbol","abstract":[{"text":"ZDKAnswerBot is responsible for initialization of","type":"text"},{"text":" ","type":"text"},{"text":"the SDK and manages the backend configuration.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBot\/provider"]},{"identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBot\/instance"],"title":"Type Properties"},{"title":"Type Methods","identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBot\/initialize(withZendesk:support:)"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK"]]},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/SQ","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/SH"],"kind":"relationships","title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(ZDKAnswerBot) "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AnswerBot"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/answerbotproviderssdk\/answerbot"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/answerbotproviderssdk\/answerbot"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.AnswerBotProvidersSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK":{"abstract":[],"title":"AnswerBotProvidersSDK","kind":"symbol","url":"\/documentation\/answerbotproviderssdk","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBot":{"type":"topic","url":"\/documentation\/answerbotproviderssdk\/answerbot","title":"AnswerBot","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AnswerBot","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AnswerBot"}],"abstract":[{"type":"text","text":"ZDKAnswerBot is responsible for initialization of"},{"type":"text","text":" "},{"text":"the SDK and manages the backend configuration.","type":"text"}],"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBot"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBot/provider":{"type":"topic","abstract":[{"type":"text","text":"AnswerBot Provider access"}],"kind":"symbol","title":"provider","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"provider","kind":"identifier"},{"kind":"text","text":": "},{"text":"AnswerBotProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKAnswerBotProvider"}],"navigatorTitle":[{"kind":"identifier","text":"provider"}],"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBot\/provider","url":"\/documentation\/answerbotproviderssdk\/answerbot\/provider"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBot/instance":{"type":"topic","url":"\/documentation\/answerbotproviderssdk\/answerbot\/instance","title":"instance","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"instance","kind":"identifier"},{"kind":"text","text":": "},{"text":"AnswerBot","kind":"typeIdentifier","preciseIdentifier":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKAnswerBot"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"instance"}],"abstract":[{"text":"Returns an instance of ","type":"text"},{"code":"AnswerBot","type":"codeVoice"},{"type":"text","text":" (singleton)"}],"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBot\/instance"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBot/initialize(withZendesk:support:)":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"initialize","kind":"identifier"},{"kind":"text","text":"("},{"text":"withZendesk","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Zendesk","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicZendesk","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"support"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Support","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKSupport"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBot\/initialize(withZendesk:support:)","role":"symbol","abstract":[{"type":"text","text":"Initializes AnswerBot with Zendesk instance and Support - e.g. AnswerBot.initialize(withZendesk: Zendesk.instance, support: Support.instance!)"}],"type":"topic","url":"\/documentation\/answerbotproviderssdk\/answerbot\/initialize(withzendesk:support:)","title":"initialize(withZendesk:support:)","navigatorTitle":[{"kind":"identifier","text":"initializeWithZendesk:support:"}],"kind":"symbol"},"doc://com.zendesk.AnswerBotProvidersSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.AnswerBotProvidersSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/objc(cs)NSObject"},"doc://com.zendesk.AnswerBotProvidersSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/SH"},"doc://com.zendesk.AnswerBotProvidersSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/SQ"},"doc://com.zendesk.AnswerBotProvidersSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.AnswerBotProvidersSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/objc(pl)NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","value":"ZDKAnswerBot","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKAnswerBot"}],"op":"replace"},{"value":[{"text":"ZDKAnswerBot","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBot\/provider"]},{"title":"Type Properties","identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBot\/instance"]},{"title":"Type Methods","identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBot\/initialize(withZendesk:support:)"]}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKAnswerBot"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ZDKAnswerBot","op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBot\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBot\/fragments","value":[{"kind":"identifier","text":"ZDKAnswerBot"}]},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBot~1provider\/title","op":"replace","value":"provider"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBot~1provider\/fragments","value":[{"text":"provider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBot~1instance\/title","value":"instance"},{"value":[{"text":"instance","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBot~1instance\/fragments"},{"value":"initializeWithZendesk:support:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBot~1initialize(withZendesk:support:)\/title"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBot~1initialize(withZendesk:support:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"initializeWithZendesk:support:","kind":"identifier"}]}]}]}