{"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/SQ","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/SH","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/SY"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"metadata":{"symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RejectionReason"}],"roleHeading":"Enumeration","navigatorTitle":[{"kind":"identifier","text":"RejectionReason"}],"title":"RejectionReason","modules":[{"name":"AnswerBotProvidersSDK"}],"role":"symbol","externalID":"c:@M@AnswerBotProvidersSDK@E@ZDKRejectionReason"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/RejectionReason"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(ZDKRejectionReason) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"RejectionReason","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/answerbotproviderssdk\/rejectionreason"]},{"paths":["\/documentation\/answerbotproviderssdk\/rejectionreason"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/RejectionReason\/notRelated","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/RejectionReason\/relatedButDidntAnswer","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/RejectionReason\/unknown"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/RejectionReason\/init(rawValue:)"],"title":"Initializers"},{"title":"Default Implementations","identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/RejectionReason\/Equatable-Implementations","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/RejectionReason\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/RejectionReason/relatedButDidntAnswer":{"url":"\/documentation\/answerbotproviderssdk\/rejectionreason\/relatedbutdidntanswer","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"relatedButDidntAnswer","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/RejectionReason\/relatedButDidntAnswer","abstract":[],"title":"RejectionReason.relatedButDidntAnswer","navigatorTitle":[{"kind":"identifier","text":"ZDKRejectionReasonRelatedButDidntAnswer"}],"kind":"symbol"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/RejectionReason/Equatable-Implementations":{"type":"topic","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/RejectionReason\/Equatable-Implementations","kind":"article","role":"collectionGroup","abstract":[],"title":"Equatable Implementations","url":"\/documentation\/answerbotproviderssdk\/rejectionreason\/equatable-implementations"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK":{"abstract":[],"title":"AnswerBotProvidersSDK","kind":"symbol","url":"\/documentation\/answerbotproviderssdk","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK"},"doc://com.zendesk.AnswerBotProvidersSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/SH"},"doc://com.zendesk.AnswerBotProvidersSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/SQ"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/RejectionReason/unknown":{"role":"symbol","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/RejectionReason\/unknown","title":"RejectionReason.unknown","type":"topic","abstract":[],"url":"\/documentation\/answerbotproviderssdk\/rejectionreason\/unknown","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unknown"}],"navigatorTitle":[{"text":"ZDKRejectionReasonUnknown","kind":"identifier"}],"kind":"symbol"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/RejectionReason/notRelated":{"abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/answerbotproviderssdk\/rejectionreason\/notrelated","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"notRelated","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKRejectionReasonNotRelated","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/RejectionReason\/notRelated","title":"RejectionReason.notRelated"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/RejectionReason/init(rawValue:)":{"abstract":[],"title":"init(rawValue:)","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/RejectionReason\/init(rawValue:)","role":"symbol","kind":"symbol","url":"\/documentation\/answerbotproviderssdk\/rejectionreason\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"type":"topic"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/RejectionReason":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RejectionReason"}],"title":"RejectionReason","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/RejectionReason","url":"\/documentation\/answerbotproviderssdk\/rejectionreason","role":"symbol","navigatorTitle":[{"text":"RejectionReason","kind":"identifier"}]},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/RejectionReason/RawRepresentable-Implementations":{"abstract":[],"kind":"article","role":"collectionGroup","url":"\/documentation\/answerbotproviderssdk\/rejectionreason\/rawrepresentable-implementations","type":"topic","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/RejectionReason\/RawRepresentable-Implementations","title":"RawRepresentable Implementations"},"doc://com.zendesk.AnswerBotProvidersSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/SY"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"ZDKRejectionReason"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"ZDKRejectionReason","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKRejectionReason","kind":"identifier"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/RejectionReason\/notRelated","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/RejectionReason\/relatedButDidntAnswer","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/RejectionReason\/unknown"],"title":"Enumeration Cases"}],"path":"\/topicSections","op":"replace"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKRejectionReason"},{"text":": ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"ZDKRejectionReasonRelatedButDidntAnswer","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1RejectionReason~1relatedButDidntAnswer\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1RejectionReason~1relatedButDidntAnswer\/fragments","value":[{"kind":"identifier","text":"ZDKRejectionReasonRelatedButDidntAnswer"}]},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1RejectionReason~1unknown\/title","value":"ZDKRejectionReasonUnknown","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1RejectionReason~1unknown\/fragments","value":[{"text":"ZDKRejectionReasonUnknown","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1RejectionReason~1notRelated\/title","value":"ZDKRejectionReasonNotRelated","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKRejectionReasonNotRelated"}],"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1RejectionReason~1notRelated\/fragments","op":"replace"},{"op":"replace","value":"ZDKRejectionReason","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1RejectionReason\/title"},{"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1RejectionReason\/fragments","value":[{"kind":"identifier","text":"ZDKRejectionReason"}],"op":"replace"}]}]}