{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"enabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettings"]]},"metadata":{"role":"symbol","symbolKind":"property","externalID":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKAnswerBotSettings(py)enabled","modules":[{"name":"AnswerBotProvidersSDK"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"enabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"enabled","kind":"identifier"}],"title":"enabled","roleHeading":"Instance Property"},"abstract":[{"type":"text","text":"A "},{"code":"Bool","type":"codeVoice"},{"type":"text","text":" indicates whether Answer Bot is enabled"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/answerbotproviderssdk\/answerbotsettings\/enabled"]},{"paths":["\/documentation\/answerbotproviderssdk\/answerbotsettings\/enabled"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettings\/enabled","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotSettings":{"abstract":[{"type":"text","text":"The AnswerBot Settings model"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AnswerBotSettings","kind":"identifier"}],"navigatorTitle":[{"text":"AnswerBotSettings","kind":"identifier"}],"url":"\/documentation\/answerbotproviderssdk\/answerbotsettings","title":"AnswerBotSettings","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettings"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotSettings/enabled":{"type":"topic","navigatorTitle":[{"text":"enabled","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotSettings\/enabled","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"enabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","title":"enabled","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"Bool"},{"type":"text","text":" indicates whether Answer Bot is enabled"}],"url":"\/documentation\/answerbotproviderssdk\/answerbotsettings\/enabled"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK":{"url":"\/documentation\/answerbotproviderssdk","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK","kind":"symbol","type":"topic","abstract":[],"title":"AnswerBotProvidersSDK","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"enabled"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"enabled","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"enabled"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"ZDKAnswerBotSettings","op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotSettings\/title"},{"value":[{"text":"ZDKAnswerBotSettings","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotSettings\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotSettings~1enabled\/title","value":"enabled"},{"value":[{"text":"enabled","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotSettings~1enabled\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}