{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/answerbotproviderssdk\/answerbotdispatcherresponse\/data"]},{"paths":["\/documentation\/answerbotproviderssdk\/answerbotdispatcherresponse\/data"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK","doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotDispatcherResponse"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotDispatcherResponse\/data","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"data","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","externalID":"c:@M@AnswerBotProvidersSDK@objc(cs)ZDKAnswerBotDispatcherResponse(py)data","symbolKind":"property","title":"data","roleHeading":"Instance Property","modules":[{"name":"AnswerBotProvidersSDK"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"data","kind":"identifier"},{"kind":"text","text":": "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"data","kind":"identifier"}]},"references":{"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotDispatcherResponse/data":{"role":"symbol","title":"data","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotDispatcherResponse\/data","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"data","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"data"}],"url":"\/documentation\/answerbotproviderssdk\/answerbotdispatcherresponse\/data"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK/AnswerBotDispatcherResponse":{"role":"symbol","title":"AnswerBotDispatcherResponse","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK\/AnswerBotDispatcherResponse","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AnswerBotDispatcherResponse","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AnswerBotDispatcherResponse"}],"url":"\/documentation\/answerbotproviderssdk\/answerbotdispatcherresponse"},"doc://com.zendesk.AnswerBotProvidersSDK/documentation/AnswerBotProvidersSDK":{"abstract":[],"title":"AnswerBotProvidersSDK","kind":"symbol","url":"\/documentation\/answerbotproviderssdk","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.AnswerBotProvidersSDK\/documentation\/AnswerBotProvidersSDK"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"data","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"data"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" * "},{"kind":"identifier","text":"data"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"data","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotDispatcherResponse~1data\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotDispatcherResponse~1data\/fragments","value":[{"kind":"identifier","text":"data"}]},{"op":"replace","value":"ZDKAnswerBotDispatcherResponse","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotDispatcherResponse\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.AnswerBotProvidersSDK~1documentation~1AnswerBotProvidersSDK~1AnswerBotDispatcherResponse\/fragments","value":[{"kind":"identifier","text":"ZDKAnswerBotDispatcherResponse"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}